---

- name: Install websites from github.
  become_user: "{{ websites_user }}"
  git:
    repo: '{{ item.repo_https_base_url }}/{{ item.repo_name }}.git'
    dest: "/opt/{{ websites_user }}/{{ item.repo_name }}"
    version: master
    force: yes
  with_items: "{{ websites }}"

- name: Install packages based on package.json.
  become_user: "{{ websites_user }}"
  npm:
    path: "/opt/{{ websites_user }}/{{ websites[0].repo_name }}/{{ item }}"
  with_items:
    - backend
    - frontend

- name: Build react frontend
  tags: mern
  become_user: "{{ websites_user }}"
  command: "/usr/bin/npm run build"
  args:
    chdir: "/opt/{{ websites_user }}/{{ item.repo_name }}/frontend"
  register: build_result
  with_items: "{{ websites }}"

- name: Creating a systemd Unit File for NodeJS app
  tags: mern
  template:
    src: "mern-website.service"
    dest: "/etc/systemd/system/{{ item.repo_name }}.service"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ websites }}"

- name: Run daemon-reload before doing any other operations
  tags: mern
  systemd:
    daemon_reload: yes

- name: Enable NodeJS app service
  tags: mern
  service:
    name: "{{ item.repo_name }}"
    enabled: yes
    state: restarted
  with_items: "{{ websites }}"

- name: "Add nginx conf file mern apps"
  tags: mern
  template:
    src: mern-nginx.conf
    dest: "/etc/nginx/sites-enabled/{{ item.sub_domain }}.{{ item.main_domain }}.conf"
    force: true
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  with_items: "{{ websites }}"
